In [23]:
import pandas as pd
# df=pd.read_csv("Data/csv_food_table2.csv")
df=pd.read_excel("Data/food_table1.csv",)
df.tail()

,"Average daily intake of food group by food source and demographic characteristics, 2015–16 and 2017–18",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
114,Household income > 300% poverty line,6.23,3.94,2.29,0.86,1.06,0.04,0.33,6.27,4.01,2.25,0.9,0.93,0.02,0.4
115,Notes: See Dietary Guidelines for Americans 20...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,1Individuals who completed two-day intake reca...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,2School foods eaten by those age 20 and above ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,Source: 2015–16 and 2017–18 National Health an...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
from pandas import *
xls = ExcelFile("Data/food_table1.csv")
df = xls.parse(xls.sheet_names[0])
# print (df.to_dict())
dic=df.to_dict()
d={}
group={}
c=list(dic.keys())
g=dic[c[0]]
grouplis=["g[i]"]
for i in dic[c[0]]:
    group[g[i]]={}
print(group)

{nan: {}, 'Food group': {}, 'Added sugar (tsp)': {}, '   Total population1': {}, '      Children age 2–19': {}, '      Adults age 20–642': {}, '      Seniors age 65 and above2': {}, '      Household income < 185% poverty line': {}, '      Household income 185–300% poverty line': {}, '      Household income > 300% poverty line': {}, 'Discretionary fats (g)': {}, 'Discretionary oils (g)': {}, 'Dairy (cup)': {}, 'Fruit (cup)': {}, 'Vegetables: total (cup)': {}, 'Vegetables: potatoes (cup)': {}, 'Vegetables: tomatoes (cup)': {}, 'Vegetables: red and orange without tomatoes (cup)': {}, 'Vegetables: dark green (cup)': {}, 'Grains: total (oz)': {}, 'Grains: refined (oz)': {}, 'Grains: whole (oz)': {}, 'Protein foods (oz)': {}, 'Notes: See Dietary Guidelines for Americans 2020–2025, Appendix 3 USDA Dietary Patterns (p. 131) for definitions of food groups. NA = not available.': {}, '1Individuals who completed two-day intake recalls and were 2 years old and older.': {}, '2School foods eaten by those age 20 and above are classified as other food away from home.': {}, 'Source: 2015–16 and 2017–18 National Health and Nutrition Examination Survey (NHANES), first-day averages.': {}}

In [36]:
# file_name=input("Enter file name: ")
# lines=open(file_name)
# lines=lines.readlines()
lines=["2,3,4,5","234,2343,234,234"]
first=input("Enter 1st column length: ")
second=input("Enter 2nd column length: ")
third=input("Enter 3rd column length: ")
fourth=input("Enter 4th column length: ")
first=int(first)
second=int(second)
third=int(third)
fourth=int(fourth)
c=0
for i in lines:
    c+=1
    i=i.replace("\n","").split(",")
    if c==1:
        for e in range(len(i)):
            i[e]=lower(i[e])
            i[e][0]=upper(i[e][0])
    
    line='{:>{x1}}{:^{x2}}{:<{x3}}{:>{x4}}'.format(i[0],i[1],i[2],i[3], x1=first,x2=second,x3=third,x4=fourth)
    print(line)

TypeError: list indices must be integers or slices, not str

In [33]:
s=10
c="{:>"+str(s)+"} "
first =10
print( '{:>{x1}}'.format('foo', x1=first))

       foo